### ISSUE TITLE
UI does not reflect advanced rule settings after refeshing.

### ISSUE THREAD

**Issue by JonIsaiah** [meshifyiot/carbon-docs#106]
Issue:  UI clears advanced rule settings after saving and reloading page

Domain: nov.meshify.com

To Reproduce:  save a rule with advanced settings, then reload page.  settings are saved (api reflects changes) but the advanced settings do not appear in the UI

Affected Node: novpump
node id: 0303030303030303
rule id: 114

expected behavior:  advanced settings reflected in ui after refresh

**Comment by NateDawg90** [comment]
So the advanced settings should be saving, but it isn't immediately clear to the user, because the 'Advanced' checkbox isn't checked when there is a cron or debounce above 0. You're not able to see the changes to the timers unless you check the box. We're deploying a fix to make the checkbox responsive today though.

**Comment by NateDawg90** [comment]
Fixed and deployed on 11/17/17
