### ISSUE TITLE
New <mf-chart> horizontal axis collapses gaps in time series data

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#112]
For example, there were no datapoints sent over the weekend, but the graph below does not show a gap. It jumps directly from 11-17 to 11-20 without representing time for 11-18 or 11-19.

While the blank space (or flat line) seems unimportant, most customers like to see the horizontal axis with a linear proportion between time and length. Said differently, it's important to know if there was no data during a time period.

![image](https://user-images.githubusercontent.com/116724/33040183-e990042a-cdff-11e7-9845-dd4d72fd2103.png)

**Comment by willpopski** [comment]
I believe this can be changes looking at the gapSize property:

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-gapsize/

```
    plotOptions: {
        series: {
            gapSize: 1
        }
    }
```

**Comment by MattMadeiro** [comment]
Can you paste the URL to the chart you have pictured above?

**Comment by willpopski** [comment]
https://carbon.meshify.com/dashboard/#/folder/4122/node/8567

I’m not seeing gaps on any chart so you shouldn’t have any trouble recreating it.

**Comment by MattMadeiro** [comment]
Fixed and deployed on 11/27/17.

**Comment by willpopski** [comment]
As part of the change, the new charts look very chunky, e.g. low resolution. I'm not able to see as many data points, and when I can, the values are averaged down and so look incorrect. (see value of 4.33, below, and the actual value of 13 in the second image.)

Is there any way to correct these things?

![image](https://user-images.githubusercontent.com/116724/33335283-39f58786-d432-11e7-9abe-08d46bc3ab99.png)

![image](https://user-images.githubusercontent.com/116724/33335327-5706d7f8-d432-11e7-852f-b9e3f13ca71d.png)

**Comment by MattMadeiro** [comment]
Sampling (the averaging of points you're describing) is a default feature of Highstocks, but one we can easily disable. When I do, the Pipeline Delay chart looks like the following:

<img width="1097" alt="screen shot 2017-11-29 at 10 17 49 am" src="https://user-images.githubusercontent.com/3777742/33385591-95f4d05c-d4ee-11e7-8cba-cf13272a85ee.png">

It doesn't average the value, but because of the density of data points on either end of the chart, you'll have to zoom in before you can get the actual value from the hover tooltip. I've also fiddled with the settings a bit, so you should see the more familiar peaks and mountains in the chart than the squares we have now.

I'm not so sure the charts are low-resolution, though. They're still rendering all the data points they have available, it's just that they're crammed into both ends in order to accommodate that huge gap in data in middle. This is a natural byproduct of having linear progression along the x axis.
