### ISSUE TITLE
Opening files with uppercase characters in them is throwing 404 error

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#132]
I don't have any live examples as I had to fix them quickly.

`https://setsegschools.carbon.meshify.com/enrollment/img/Ellipsis.svg` threw 404 while `https://setsegschools.carbon.meshify.com/enrollment/img/ellipsis.svg` is working fine.

Another example:
`https://setsegschools.carbon.meshify.com/enrollment/files/SetSegHSBSensorInstallationGuide.pdf` threw error before I renamed it, `https://setsegschools.carbon.meshify.com/enrollment/files/setseghsbsensorinstallationguide.pdf` is working.

These files were accessible with uppercase characters in their name not long ago.

**Comment by NateDawg90** [comment]
In Admin, if an existing file has an uppercase character, the API will not know how to read, edit, or delete. It will return a 404. 

Due to a recent update, we now prevent files from having uppercase characters in the Admin core, but I can see how this creates a problem for uppercase files already in the system, or when files are manually added to S3.

**Comment by Ashtonian** [comment]
@balintd - how were these files uploaded? Nate is correct, the api will lower case all incoming files which is how we handle casing issues. Based on the last modified date, these were likely uploaded by hand or through some other process that needs to account for this.

**Comment by Ashtonian** [comment]
I lower cased all existing s3 files, the s3 upload tool you are using will need to be updated to lower case file names before they go into s3.
