### ISSUE TITLE
Feature: configurable expiration times for Invite/Password Reset urls

### ISSUE THREAD

**Issue by Gayle313** [meshifyiot/carbon-docs#148]
The password set and reset URL currently expires after 4 hours.  As a participant, I may not attempt to log in to Meshify for several days.  The URLs to set a password as well as reset a password need to expire 30 days after they are created.

**Comment by decker405** [comment]
Due to security concerns, we are not going to make this configurable by the end user. We are, however, going to extend user invite expiration to 7 days.

We have also updated the UI to provide a better user experience in regards to this. If the token is expired, it shows an error message stating:

`This URL is invalid or expired. Please use the forgot password link to get a new password reset email.`

It then automatically sends the user to the forgot password page, where they can request a new email to be sent to them, with a fresh (not expired) URL.

The UI change is complete, the expiration change should be completed towards the end of the week.

**Comment by decker405** [comment]
These changes are complete in both the UI and in the backend.

**Comment by balintd** [comment]
Thank you. Just to verify, both user invite and password reset URLs expire in 7 days now, right?

**Comment by Ashtonian** [comment]
yes, in the backend the tokens are currently generated the same. The templates are just different.
