### ISSUE TITLE
Combine reactions e-mail templates into user invite/pw reset email templates

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#50]
This enhancement would combine e-mail templates (and possibly sms templates) into one location. I believe it would help with the mental model of administration and help with UX of updating branding of many templates simultaneously.

**Comment by decker405** [comment]
I understand what you're driving at, but I think that keeping user-centric and reaction emails separate from one another feels a lot cleaner, mental-model-wise, since they serve very different purposes.

I made the decision to keep the template content with the Reactions to avoid yet another layer of indirection that already exists among Rules, Reactions, Notification Schemas, and Subscriptions. I think for now, having them together makes sense. I'm going to close this issue, but if we see a lot of pain arising around duplicate template content, we can open a new issue that recommends that ReactionTemplates become their own entity. Note that if we do that, it's not going to be a priority for a while as we have much bigger pain points and features to add right now.
