### ISSUE TITLE
Rules aren't Posting via API

### ISSUE THREAD

**Issue by psk788** [meshifyiot/carbon-docs#99]
Current Behavior: When I try to to create a new Rule using POST at http://hsb-carbon.meshify.com/api/rules, it is returning the GET results instead of posting the payload.

Expected Behavior: It should create a rule and not just return all the current rules.

![image](https://user-images.githubusercontent.com/9382834/32789085-e7f6f730-c928-11e7-9250-9c098a9cd97f.png)

**Comment by decker405** [comment]
Simple answer:

You should be using `https`. We set forceHttps to true for HSB's Meshify domains. You should also be using https anyways when using BasicAuth, otherwise you're sending credentials in an insecure manner.

Longer explanation:

`hsb-carbon.meshify.com` has `ForceHTTPS=true` checked for the Domain in the Admin side. This will cause a 301 redirect from `http://*` to `https://*`. All AJAX clients handle a 301 redirect during a POST by doing a GET to the new resource (for security reasons).

**Comment by willpopski** [comment]
For POST and PUT, wouldn't it be better to respond with 403 Forbidden, to avoid every person encountering this having to post a ticket? It's not just AJAX clients.. the same thing happened with other clients as well.

**Comment by Ashtonian** [comment]
if we did that, the user experience when accessing via the web UI would be a 403 rather then a proper redirect so then the user's would have to discover for themselves that its an https: issue.

**Comment by willpopski** [comment]
Web UI users don’t hit the API directly, though. Can we differentiate
between the web browsing and API?


On November 14, 2017 at 10:47:55 AM, Ashton Kinslow (
notifications@github.com) wrote:

if we did that, the user experience when accessing via the web UI would be
a 403 rather then a proper redirect so then the user's would have to
discover for themselves that its an https: issue.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/meshifyiot/carbon-docs/issues/99#issuecomment-344321341>,
or mute the thread

**Comment by Ashtonian** [comment]
I've updated the status code to 307, not all clients support it but this should help the postman behavior.
